/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as KeysRouteImport } from './routes/keys'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V1GenerateRouteImport } from './routes/v1/generate'
import { Route as V1ChatRouteImport } from './routes/v1/chat'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1GenerateRoute = V1GenerateRouteImport.update({
  id: '/v1/generate',
  path: '/v1/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ChatRoute = V1ChatRouteImport.update({
  id: '/v1/chat',
  path: '/v1/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/keys': typeof KeysRoute
  '/playground': typeof PlaygroundRoute
  '/projects': typeof ProjectsRoute
  '/v1/chat': typeof V1ChatRoute
  '/v1/generate': typeof V1GenerateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/keys': typeof KeysRoute
  '/playground': typeof PlaygroundRoute
  '/projects': typeof ProjectsRoute
  '/v1/chat': typeof V1ChatRoute
  '/v1/generate': typeof V1GenerateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/keys': typeof KeysRoute
  '/playground': typeof PlaygroundRoute
  '/projects': typeof ProjectsRoute
  '/v1/chat': typeof V1ChatRoute
  '/v1/generate': typeof V1GenerateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/keys' | '/playground' | '/projects' | '/v1/chat' | '/v1/generate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/keys' | '/playground' | '/projects' | '/v1/chat' | '/v1/generate'
  id:
    | '__root__'
    | '/'
    | '/keys'
    | '/playground'
    | '/projects'
    | '/v1/chat'
    | '/v1/generate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KeysRoute: typeof KeysRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ProjectsRoute: typeof ProjectsRoute
  V1ChatRoute: typeof V1ChatRoute
  V1GenerateRoute: typeof V1GenerateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/generate': {
      id: '/v1/generate'
      path: '/v1/generate'
      fullPath: '/v1/generate'
      preLoaderRoute: typeof V1GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/chat': {
      id: '/v1/chat'
      path: '/v1/chat'
      fullPath: '/v1/chat'
      preLoaderRoute: typeof V1ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KeysRoute: KeysRoute,
  PlaygroundRoute: PlaygroundRoute,
  ProjectsRoute: ProjectsRoute,
  V1ChatRoute: V1ChatRoute,
  V1GenerateRoute: V1GenerateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
